name: Update RSS Feed

on:
  schedule:
    # 每天运行一次 (中国时间上午10:00，对应UTC时间02:00)
    - cron: '0 2 * * *'
  workflow_dispatch:     # 允许手动触发

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run RSS merger
        run: |
          python topic_rss_merger_optimized.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f topic_merged_rss_optimized.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
