name: Update RSS Feed

on:
  schedule:
    # 美国中部时间晚上11:00 (UTC-5:00) = UTC时间早上4:00
    - cron: '0 4 * * *'
  workflow_dispatch:     # 允许手动触发

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run RSS aggregator
        run: |
          python fixed_rss_aggregator.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f final_rss.xml final_daily_news.html
          git commit -m "Update RSS feed and daily news" || echo "No changes to commit"
          git push
